version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: linder-app
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - MONGO_DB_URI=mongodb://mongo:27017
      - MONGO_DB_DATABASE=linder
    depends_on:
      - mongo
    networks:
      - linder-net

  nginx:
    image: nginx:latest
    container_name: linder-nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - linder-net

  mongo:
    image: mongo:latest
    container_name: linder-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - linder-net

volumes:
  mongo-data:

networks:
  linder-net:
    driver: bridge